name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.15.0' 

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test || echo "No tests to run" 

    - name: Run linting
      run: npm run lint || echo "No linting configured" 