name: Release Notes

on:
  release:
    types: [created] 

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Generate release notes
        id: generate_notes
        uses: softprops/action-gh-release@v1  
        with:
          body: |
            ## Release notes for ${{ github.event.release.tag_name }}:
            - **Features Added**: 
              - (List features here)
            - **Bugs Fixed**: 
              - (List bugs fixed here)

      - name: Output Release Notes
        run: echo "Release notes generated successfully." 