name: Release Notes

on:
  release:
    types: [created]

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate release notes
        uses: softprops/action-gh-release@v1
        with:
          body: |
            Release notes for ${{ github.event.release.tag_name }}:
            - Features added
            - Bugs fixed
