name: Scheduled Dependency Update

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly at midnight on Sunday

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run npm audit to check vulnerabilities
        run: npm audit

      - name: Update dependencies
        run: npm update

      - name: Push updated dependencies
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -am "Automated dependency update"
          git push origin main
